name: xxx
defaults: &defaults
  adapter:  postgres
  host:     localhost

dev:
  db: myapp
  <<: *defaults

test:
  database: myapp_test
  <<: *defaults
  ints:
    - 1
    - 2
    - 3
  float: 1.11
  fs:
    - 1.1
    - 2.2
    - 3.3
  ss:
    - a
    - b
    - c
  maps:
    - key: k1
      val: v1
      payload:
        len: 1
        hash: hhh
    - key: k2
      val: v2
      payload:
        len: 2
        hash: hhh
    - val: v3
      payload:
        len: 3
        hash: hhh
      key: k3
    - payload:
        len: 4
        hash: hhh
      nokey: k4
      noval: v4

  labels:
    - type: yaml
    - author:
        project: xrpc
        desc: 'a simple rpc framework'
        version: 1.0
        web: [baidu.com, google.com]
        <<: *defaults
        modules:
          pkg: 1
          plugin:
            - prom
            - trace
